import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: 'KTU Labwork',
    description: 'Generated by Rahul A B',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn("min-h-screen flex flex-col")}>
                <Navbar />
                <section className="sm:px-10 p-5 flex-grow">
                    {children}
                </section>
                <Footer />
            </body>
        </html>
    );
}
